
services:
  mysql:
    image: mariadb:11.6-ubi9
    container_name: next_saas_starter_mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: saas_starter
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
